/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  theme: {
    extend: {
      colors: {
        primary: "rgba(var(--primary))",
        secondary: "rgba(var(--secondary))",
        "copy-primary": "rgba(var(--copy-primary))",
        "copy-secondary": "rgba(var(--copy-secondary))",
        "copy-cta": "rgba(var(--copy-cta))",
        "toggle-bg": "rgba(var(--toggle-bg))",
        "toggle-center": "rgba(var(--toggle-center))",
        "toggle-border": "rgba(var(--toggle-border))",
        background: "rgba(var(--background))",
        border: "rgba(var(--border))",
        card: "rgba(var(--card))",
        tooltip: "rgba(var(--tooltip))",
        toolbar: "rgba(var(--toolbar))",
        delete: "rgba(var(--delete))",
        tag: "rgba(var(--tag))",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["[data-theme=light]"],
          "--primary": "36, 111, 255",
          "--secondary": "226, 244, 255",
          "--copy-primary": "0, 0, 0",
          "--copy-secondary": "83, 83, 83",
          "--copy-cta": "255, 255, 255",
          "--toggle-bg": "120, 198, 255",
          "--toggle-center": "255, 176, 21",
          "--background": "255, 255, 255",
          "--border": "0, 0, 0",
          "--card": "217, 217, 217",
          "--tooltip": "83, 83, 83",
          "--toolbar": "133, 131, 131",
          "--delete": "237, 0, 0",
          "--tag": "87, 13, 248",
        },
        dark: {
          ...require("daisyui/src/theming/themes")["[data-theme=dark]"],
          "--primary": "36, 111, 255",
          "--secondary": "38, 0, 189",
          "--copy-primary": "255, 255, 255",
          "--copy-secondary": "142, 180, 255",
          "--copy-cta": "255, 255, 255",
          "--toggle-bg": "85, 42, 255",
          "--toggle-center": "178, 185, 255",
          "--background": "0, 13, 39",
          "--border": "255, 255, 255",
          "--card": "0, 25, 74",
          "--tooltip": "17, 65, 158",
          "--toolbar": "0, 40, 115",
          "--delete": "237, 0, 0",
          "--tag": "87, 13, 248",
        },
      },
    ],
  },
};
