/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as UploadZzalIndexImport } from "./routes/Upload-Zzal/index"
import { Route as MyUploadedZzalIndexImport } from "./routes/My-Uploaded-Zzal/index"
import { Route as MyLikedZzalIndexImport } from "./routes/My-Liked-Zzal/index"
import { Route as AdminIndexImport } from "./routes/Admin/index"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const UploadZzalIndexRoute = UploadZzalIndexImport.update({
  path: "/Upload-Zzal/",
  getParentRoute: () => rootRoute,
} as any)

const MyUploadedZzalIndexRoute = MyUploadedZzalIndexImport.update({
  path: "/My-Uploaded-Zzal/",
  getParentRoute: () => rootRoute,
} as any)

const MyLikedZzalIndexRoute = MyLikedZzalIndexImport.update({
  path: "/My-Liked-Zzal/",
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: "/Admin/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/Admin/": {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    "/My-Liked-Zzal/": {
      preLoaderRoute: typeof MyLikedZzalIndexImport
      parentRoute: typeof rootRoute
    }
    "/My-Uploaded-Zzal/": {
      preLoaderRoute: typeof MyUploadedZzalIndexImport
      parentRoute: typeof rootRoute
    }
    "/Upload-Zzal/": {
      preLoaderRoute: typeof UploadZzalIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminIndexRoute,
  MyLikedZzalIndexRoute,
  MyUploadedZzalIndexRoute,
  UploadZzalIndexRoute,
])

/* prettier-ignore-end */
